- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install vsftpd
    yum:
     name: vsftpd
     state: latest
  - name: Starting vsftpd
    service:
     name: vsftpd
     state: started
  - name: Enable vsftpd
    service:
     name: vsftpd
     enabled: yes
  - name: Install firewalld
    yum:
     name: firewalld
     state: latest
  - name: Starting firewalldd
    service:
     name: firewalld
     state: started
